version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: learn2earn_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: learn2earn_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: learn2earn_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: learn2earn_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
